app_show_product:
    path: /products/{id}
    methods: [GET]
    defaults:
        _controller: App\Controller\ShowProductAction

app_show_cart:
    path: /cart
    methods: [GET]
    defaults:
        _controller: App\Controller\ShowCartAction

app_add_product_to_cart:
    path: /products/add
    methods: [POST]
    defaults:
        _controller: App\Controller\AddProductToCartAction
