parameters:
    locale: 'en'

services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: true;

    app.repository.product:
        class: Doctrine\ORM\EntityRepository
        factory: "doctrine.orm.entity_manager:getRepository"
        arguments:
            - "App\\Entity\\Product"

    App\Controller\ShowProductAction:
        arguments:
            - "@twig"
            - "@app.repository.product"



